name: push
on:
  push:
    branches:
      - main
      - master
    tags:
      - v*

jobs:
  lint:
    name: Run S2I-build
    runs-on: ubuntu-20.04

    env:
      IMAGE_NAME: quarkus-tasks
      TAGS: v1 ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: '.'
          # Builder image for a java project
          builder_image: 'registry.access.redhat.com/openjdk/openjdk-11-rhel7'
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: quay.io/${{ env.GITHUB_REPOSITORY_OWNER }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}